# Arquivo de configuração para deploy no Google Cloud Run

steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/thermal-comfort-api:$BUILD_ID', './api']
  
  # Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/thermal-comfort-api:$BUILD_ID']
  
  # Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'thermal-comfort-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/thermal-comfort-api:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '256Mi'  # Memória mínima viável para FastAPI
      - '--cpu'
      - '0.25'  # CPU mínima viável (1/4 de vCPU)
      - '--min-instances'
      - '0'  # Scale to zero quando não usar
      - '--max-instances'
      - '2'  # Máximo 2 instâncias
      - '--concurrency'
      - '10'  # 10 requests simultâneos
      - '--timeout'
      - '300'  # Timeout de 5 minutos

images:
  - 'gcr.io/$PROJECT_ID/thermal-comfort-api:$BUILD_ID'

# Configurações mínimas para Cloud Build
options:
  machineType: 'E2_STANDARD_2'  # Máquina mínima viável para builds Docker
  diskSizeGb: '20'  # Disco suficiente para Docker layers
  substitutionOption: 'ALLOW_LOOSE'
  logging: 'CLOUD_LOGGING_ONLY'
  
# Timeout adequado
timeout: '600s'  # 10 minutos - tempo adequado para build